defaultIndent: "\t"

# environments that have tab delimiters, add more
# as needed
lookForAlignDelims:
  tabbing: 1

modifyLineBreaks:
  textWrapOptions:
    columns: 80 # number of columns
    perCodeBlockBasis: 1 # per-code-block wrap
    beforeFindingChildCodeBlocks: 1 # wrap *before* finding child code blocks
    mainDocument: 1 # apply to main document
    afterHeading: 1 #   after headings
    items: 1 #   within items
  removeParagraphLineBreaks: # remove line breaks within paragraphs
    mainDocument: 1
    afterHeading: 1
    items: 1
    beforeTextWrap: 1 # before wrapping text
