name: domain-adaptation
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - kedro=0.18.0
  - pandas=1.4.2
  - opencv=4.5.5
  - scikit-learn=1.1.0
  - pyarrow=8.0.0
  - tqdm=4.64.0
  - umap-learn=0.5.3
  - notebook
  - pytorch
  - torchvision
  - torchaudio